title: "Designing LLM Applications with Partial Autonomy"
description: "Building Iron Man Suits for Human Intelligence"
theme: minima
show_excerpts: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
