title: "Designing LLM Applications with Partial Autonomy: Building \"Iron Man Suits\" for Human Intelligence"
description: "Building Iron Man Suits for Human Intelligence"
theme: minima
show_excerpts: false
show_downloads: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
